version: "3.7"
services:

  grpcserver:
    container_name: grpcserver
    build:
      context: .
      dockerfile: grpcserver/Dockerfile
    networks:
      grpc_network:
    ports:
      - "5000:80"
  
  redisserver:
    container_name: redisserver
    image: redis
    ports: 
      - "5002:6379"
    networks:
      grpc_network:

networks:
  grpc_network: