version: '3.1'

services:
  grpcserver:
    image: grpserver
    build:
      context: .
      dockerfile: grpcserver/Dockerfile
    ports:
      - 5001:5001
    # environment:
      # - SERVER_ADDRESS=https:\\localhost:5001